### ISSUE TITLE
Crowdsale and token logic should be in separate contracts

### ISSUE THREAD

**Issue by tommyz7** [Onessus/crowdsale-draft#4]
Token contract should not contain crowdsale logic. There should be separate crowdsale contract that controls token and handles crowdsale. 
See: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/MintableToken.sol

**Comment by 3th3r3um** [comment]
I agree that this is probably best practice. I've created a new branch called split-contracts. I'll work on separating out the crowdsale logic and make the changes in the new branch. Then we can work on combining it into the main branch.

**Comment by tommyz7** [comment]
Also please keep in mind that there will be probably multiple crowdsales (preICO and ICO at least). Open zeppelin contract does not account for that. One example of the solution you can see in my repo https://github.com/tommyz7/hydrocoin

**Comment by 3th3r3um** [comment]
I don't like the idea of having multiple contracts for the preICO/ICO. I agree with separating the purchase/crowdsale logic from the normal token logic by using two separate contracts. But I'd prefer just have one well-written contract for each crowdsale/round. Then we can just allow the owner to set the parameters for each round (like rate and supply).

**Comment by tommyz7** [comment]
In this case it's not that important if you use one or two sale contracts since there isn't that much functionality and requirements are well known.

Just keep in mind that any software development, you'll update it all the time but you can't do it here, contracts are non changeable. That's why during design you should split functionality as much as possible and make whole system as modular as possible. In this case it would mean separate crowdsale contracts.

**Comment by 3th3r3um** [comment]
I'm not arguing against modularity, just complexity. But I agree that we can work out how many sale contracts to have later.

 I've pushed code to the split-contracts branch that keeps the crowdsale logic separate from the token logic. I haven't had a chance to update the tests or anything, but feel free to look over the contracts.
